version: '2'

services:

  web:
    image: nginx:latest
    container_name: 'nginx'
    ports:
        - 8089:80
    volumes:
        - ../source/:/var/www/html
        - ./microServices/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
    networks:
      - app-network

  php:
    build: microServices/phpfpm
    container_name: 'phpfpm'
#    command: --storage-driver=overlay
    volumes:
        - ../source/:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: "bridge"
