<?php


namespace Tests\Unit\App\Criterias;


use App\Services\HotelService;
use Tests\MockData\HotelsMockData;
use Tests\TestCase;

class PriceSortCriteriaTest extends TestCase
{
    private $hotelService;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->hotelService= new HotelService();
    }

    public function testHotelPriceSortCriteriaTest()
    {
        $hydratedHotels= $this->prepareHotelsList($this->hotels);
        $hydratedHotels= $this->hotelService->setHotels($hydratedHotels)->combinHotels()->getHotels();
        $sortedHotels= $this->hotelService->SortHotelsByRoomPrice($hydratedHotels)->getHotels();
        foreach ($sortedHotels as $sortedHotel){
            $prices=[];
            foreach ($sortedHotel->getRooms() as $room){
                $prices[]= $room->getTotalPrice();
            }
            $this->assertTrue(min($prices)==$sortedHotel->getRooms()[0]->getTotalPrice());
            $this->assertTrue($prices[2]>$prices[1]);
        }
    }
}
